config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'pages/home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :users, only: [:index, :show] do
    resources :follows
  end
  resources :posts, only: [:index, :show, :new, :create] do 
    resources :likes
    get 'tldr'
  end
  resources :topics, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bipolar.rb
class Bipolar < ApplicationRecord
    belongs_to :member, class_name: "User"
    belongs_to :owner, class_name: "User"
end

app/models/follow.rb
class Follow < ApplicationRecord
    belongs_to :follower, class_name: 'User'
    belongs_to :followee, class_name: 'User'
  end

app/models/hate.rb
class Hate < ApplicationRecord
    belongs_to :upvote, class_name: "Like"
    belongs_to :downvote, class_name: "Like"
end

app/models/like.rb
class Like < ApplicationRecord

    belongs_to :user
    belongs_to :post

end

app/models/post.rb
class Post < ApplicationRecord

    has_many :likes
    belongs_to :user 
    belongs_to :topic

    validates :title, presence: true
    validates :content, presence: true

    def self.top_post
        post = self.all.sort {|a, b| b.likes.count <=> a.likes.count}
        post.take(1)
    end

    def tl_dr
            self.content.split.size > 15
    end

    def self.most_popular
        post = self.all.sort {|a, b| b.likes.count <=> a.likes.count}
        post.take(3)
    end

    def self.filter_new
        post = self.all.sort {|a| a.created_at}
        post.take(3)
    end

    def has_pics?
        if self.img_url.empty?
            false
        else
            true
        end
    end


end

app/models/topic.rb
class Topic < ApplicationRecord

    has_many :posts
    has_many :users, through: :posts

    def self.top_topic
        max_num = 0
        self.all.find do |topic|
            max_num = topic.posts.count if topic.posts.count > max_num
        end
    end

    def self.trending
        yeet = self.all.sort {|a, b| b.posts.count <=> a.posts.count}
        yeet.take(3)
    end

    def self.ordered
        yeet = self.all.sort {|a, b| b.posts.count <=> a.posts.count}
    end

end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_many :likes
    has_many :posts
    has_many :topics, through: :posts

    has_many :followed_users, foreign_key: :follower_id, class_name: 'Follow'
    has_many :followees, through: :followed_users

    has_many :following_users, foreign_key: :followee_id, class_name: 'Follow'
    has_many :followers, through: :following_users

    def self.top_contributer
        max_num = 0
        self.all.find do |user|
            max_num = user.posts.count if user.posts.count > max_num
        end
    end

end

app/controllers/hates_controller.rb
class HatesController < ApplicationController
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
before_action :find_post
   def create
     @post.likes.create(user_id: 1)
     redirect_to post_path(@post)
   end

   private

   def find_post
     @post = Post.find(params[:post_id])
   end

 end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bipolars_helper.rb
module BipolarsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/hates_helper.rb
module HatesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reddit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<head>

</head>
<div class="title_page">
    <h1>Underground Reddit</h1>
</div>

<br>
<img src="https://www.pinclipart.com/picdir/big/569-5695604_reddit-logo-clipart.png" width="200" height="250" alt="Bootleg Reddit">
<br><br>
<h3> <%= link_to "New Post", new_post_path %>
<br><br>
<h3> <label> Top Post:  <% if Post.top_post == nil %>
                            <%= "There is no top Post atm T_T" %>
                        <% else %>
                            <%= link_to Post.top_post[0][:title], post_path(Post.top_post) %> </label> </h3>
                            <label> Post Likes:  <%= Post.top_post[0].likes.count %> </label>
                        <% end %>
<br><br><br>
<h3> <label> Top Contributer:  <%= link_to User.top_contributer.username, user_path(User.top_contributer) %> </label> </h3>
<br>
<label> Contributer Posts:  <%= User.top_contributer.posts.count %> </label>
<br><br>
<h3> <label> Top Topic:  <%= link_to Topic.top_topic.title, topic_path(Topic.top_topic) %> </label> </h3>
<br>
<label> Topic Posts:  <%= Topic.top_topic.posts.count %> </label>
<br><br>
<h3> <label> Trending Topics: 
<br><br>
<ol>
<% Topic.trending.each do |topic| %>
    <li> |<%= link_to topic.title, topic_path(topic) %>| </li> 
<%end%>
</ol> </label> </h3> 
<h3> <label> Most Popular Posts: 
<br><br>
<ol>
<% Post.most_popular.each do |post| %>
    <li> |<%= link_to post.title, post_path(post) %>| </li> 
<%end%>
</ol> </label> </h3>
<h3> <label> New Posts: 
<br><br>
<ol>
<% Post.filter_new.each do |post| %>
    <li> |<%= link_to post.title, post_path(post) %>| </li> 
<%end%>
</ol> </label> </h3>
<h3> <label> Posts with Pictures: 
<br><br>
<ol>
<% Post.all.each do |post| %>
    <% if post.has_pics? then %>
    <li> |<%= link_to post.title, post_path(post) %>| </li> 
    <%end%>
<%end%>
</ol> </label> </h3>
<br><br>
<br><br>
<%= link_to "All Topics", topics_path %>