config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'pages/home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :users, only: [:index, :show] do
    resources :follows
  end
  resources :posts, only: [:index, :show, :new, :create] do 
    resources :likes
    get 'tldr'
  end
  resources :topics, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bipolar.rb
class Bipolar < ApplicationRecord
    belongs_to :member, class_name: "User"
    belongs_to :owner, class_name: "User"
end

app/models/follow.rb
class Follow < ApplicationRecord
    belongs_to :follower, class_name: 'User'
    belongs_to :followee, class_name: 'User'
  end

app/models/hate.rb
class Hate < ApplicationRecord
    belongs_to :upvote, class_name: "Like"
    belongs_to :downvote, class_name: "Like"
end

app/models/like.rb
class Like < ApplicationRecord

    belongs_to :user
    belongs_to :post

end

app/models/post.rb
class Post < ApplicationRecord

    has_many :likes
    belongs_to :user 
    belongs_to :topic

    validates :title, presence: true
    validates :content, presence: true

    def self.top_post
        post = self.all.sort {|a, b| b.likes.count <=> a.likes.count}
        post.take(1)
    end

    def tl_dr
            self.content.split.size > 15
    end

    def self.most_popular
        post = self.all.sort {|a, b| b.likes.count <=> a.likes.count}
        post.take(3)
    end

    def self.filter_new
        post = self.all.sort {|a| a.created_at}
        post.take(3)
    end

    def has_pics?
        if self.img_url.empty?
            false
        else
            true
        end
    end


end

app/models/topic.rb
class Topic < ApplicationRecord

    has_many :posts
    has_many :users, through: :posts

    def self.top_topic
        max_num = 0
        self.all.find do |topic|
            max_num = topic.posts.count if topic.posts.count > max_num
        end
    end

    def self.trending
        yeet = self.all.sort {|a, b| b.posts.count <=> a.posts.count}
        yeet.take(3)
    end

    def self.ordered
        yeet = self.all.sort {|a, b| b.posts.count <=> a.posts.count}
    end

end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_many :likes
    has_many :posts
    has_many :topics, through: :posts

    has_many :followed_users, foreign_key: :follower_id, class_name: 'Follow'
    has_many :followees, through: :followed_users

    has_many :following_users, foreign_key: :followee_id, class_name: 'Follow'
    has_many :followers, through: :following_users

    def self.top_contributer
        max_num = 0
        self.all.find do |user|
            max_num = user.posts.count if user.posts.count > max_num
        end
    end

end

app/controllers/hates_controller.rb
class HatesController < ApplicationController
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
before_action :find_post
   def create
     @post.likes.create(user_id: 1)
     redirect_to post_path(@post)
   end

   private

   def find_post
     @post = Post.find(params[:post_id])
   end

 end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    def index
        @posts = Post.all 
    end 

    def show 
        @post = Post.find(params[:id])
    end

    def tldr
        @post = Post.find(params[:post_id])
    end

    def new
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)

        @post.save

        redirect_to post_path(@post)
    end

    private

    def post_params
        params.require(:post).permit(:title, :content, :img_url, :user_id, :topic_id)
    end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

    def index
        @topics = Topic.all 
    end

    def show 
        @topic = Topic.find(params[:id])
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bipolars_helper.rb
module BipolarsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/hates_helper.rb
module HatesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/index.html.erb
<h1> All Posts </h1>
<br><br>

<h3>
<% @posts.each do |post| %>
   <li> <%= link_to post.title, post_path(post) %>: <br> <%= post.content %> </li>
<% end %> 
</h3>

app/views/posts/new.html.erb
<h1>Create a New Post!</h1>
<br><br>
<div>
<h3>

<%= form_for @post do |f| %>
    <%= f.label "Title: " %>
    <%= f.text_field :title %>
    <br><br>

    <%= f.label "Content: " %>
    <%= f.text_field :content %>
    <br><br>

    <%= f.label "Image: " %>
    <%= f.text_field :img_url %>
    <br><br>

    <%= f.collection_select(:user_id, User.all, :id, :username, prompt: "Select a User!")%>
    <br><br><br>

    <%= f.collection_select(:topic_id, Topic.all, :id, :title, prompt: "Select a Topic!")%>
    <br><br><br>


    <%= f.submit %>
<%end%>
</h3>
</div>
<br><br>
<h3>
    <ul>
        <% @post.errors.full_messages.each do |message| %>
            <li> <%= message %> </li>
        <% end %>
    </ul> 

</h3>

app/views/posts/show.html.erb
<h1> <%= @post.title %> </h1>
<h3> User: <%= link_to @post.user.username, user_path(@post.user) %> </h3>

<h3> <%= @post.content %> </h3>
<% if @post.has_pics? then %>
<br><br>
<img src="<%=@post.img_url%>">
<br><br>
<%end%>
<h3> Likes: <br>
<%= @post.likes.count %>
</h3>

<%= button_to 'Like', post_likes_path(@post), method: :post %>

<h3> Topic : <br>
<%= link_to @post.topic.title, topic_path(@post.topic) %>
</h3>
<br><br>
<%= link_to "All Posts", posts_path %>
<% if @post.tl_dr == true %>
    <%= link_to "TL:DR", post_tldr_path(@post) %>
<% end %>
<br><br>
<%= link_to "Home Page", root_path %>

app/views/posts/tldr.html.erb
<img src="<%=@post.img_url%>">
<br><br>
<%= link_to "Home Page", root_path %>

app/views/topics/index.html.erb
<ol> <h1> Ordered by most popular: <br><br>
<% Topic.ordered.each do |topic| %>
    <li> <%= link_to topic.title, topic_path(topic) %> </li>
    <br><br>
<% end %>
</h1> </ol>

app/views/topics/show.html.erb
<h1> <%= @topic.title %> </h1>
<br><br>
<h3> <ul>
<% @topic.posts.each do |post| %>
    <li> <%= link_to post.title, post_path(post) %>: <br> <%= post.content %> </li>
    <br><br>
<%end%>
</ul> </h3>
<br><br>
<%= link_to "Home Page", root_path %>

app/views/users/index.html.erb
<h1> All Users </h1>
<br><br>
<% @users.each do |a| %>
    <li> <%= link_to a.username, user_path(a) %> </li>
<%end%>

app/views/users/show.html.erb
<h1> <%= @user.username %>'s Page </h1>
<h3> Followers: <%= @user.followers.count %> </h3>
<br><br>
<h3> <%= @user.username %>'s Posts </h3>
<br>
<h4> <% @user.posts.each do |post| %>
    <li> <%= link_to post.title, post_path(post) %> </li> <br>
<% end %> </h4>

<%= button_to 'Follow', user_follows_path(@user), method: :post %>